version: "3.8"

services:
  oci-linux-builder:
    build:
      context: .
      dockerfile: Dockerfile.x86
    image: oci-linux-builder:latest
    container_name: oci-linux-builder
    volumes:
      - ./output:/build/output
      - ./config:/build/config
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    devices:
      - /dev/dri:/dev/dri
    network_mode: host
    privileged: true
    tty: true
    stdin_open: true
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
